name: monisto
version: 0.0.0.0
synopsis: An entity database
description: ...
author: Oleg Grenrus <oleg.grenrus@iki.fi>
maintainer: Oleg Grenrus <oleg.grenrus@iki.fi>
license: BSD3
github: futurice/haskell-mega-repo
category: Web
tested-with: GHC==7.8.4, GHC==7.10.3, GHC==8.0.1
extra-source-files:
- README.md

ghc-options: -Wall

library:
  default-extensions:
    - ConstraintKinds
    - DataKinds
    - DeriveDataTypeable
    - DeriveFoldable
    - DeriveFunctor
    - DeriveGeneric
    - DeriveTraversable
    - GADTs
    - KindSignatures
    - NoImplicitPrelude
    - ScopedTypeVariables
    - TypeFamilies
    - TypeOperators
  source-dirs: src
  dependencies:
    - base                  >=4.7   && <4.10
    - base-compat
    - dependent-map
    - dependent-sum
    - futurice-prelude
    - generics-sop
